name: CI
on: [push, pull_request]

jobs:
  build:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        py: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.py }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.py }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          pip install pytest pytest-cov

      - name: Install calabar
        run: |
          pip install .

      - name: Run Unit Tests
        run: |
          pytest -vvv --color=yes --cov=calabar --cov-append tests/unit

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
