name: CI
on: [push, pull_request]

jobs:
  build:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        py: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.py }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.py }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Install calabar
        run: |
          pip install .

      - name: Run Unit Tests
        run: |
          pytest -vvv --color=yes --cov=calabar --cov-append tests/unit

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
